### ISSUE TITLE
Unable to access web interface Non-SSL / SSL

### ISSUE THREAD

**Issue by b3ck** [dirtyredz/Dirty-Server-Manager#1]
Hello I have tried to use the web interface with both the default PHP Server [NON-SSL] (8080), and the Apache [SSL] (443) all the ports are open and I have used the command to start it, still nothing..  any ideas?

Thanks in Advance & Kind Regards,
-b3ck

**Comment by dirtyredz** [comment]
OMG im so sry, I got a new phone and my notifications have all been fucked up. I never even saw this issue.

Im assuming your using the apache installer script? if so that script has been updated with 1.1.7, i suggest trying the installer again.

also if the error continues, give me the last few lines in the /hom/avorion/avorion-manager/webroot/error.log file thxs
